/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/analyses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Analyses
     * @description Stored analyses, newest first.
     */
    get: operations["list_analyses_api_v1_analyses_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/analyses/{analysis_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Analysis */
    get: operations["get_analysis_api_v1_analyses__analysis_id__get"];
    put?: never;
    post?: never;
    /**
     * Delete Analysis
     * @description `409` when executions refer to it: their audit trail must keep its source.
     */
    delete: operations["delete_analysis_api_v1_analyses__analysis_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/analyses/{analysis_id}/executions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Analysis Executions
     * @description Executions created from this analysis (also readable while execution is off).
     */
    get: operations["get_analysis_executions_api_v1_analyses__analysis_id__executions_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/analyses/{analysis_id}/executions/{execution_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Analysis Execution
     * @description One execution of this analysis with its steps and its verified audit log (read-only).
     */
    get: operations["get_analysis_execution_api_v1_analyses__analysis_id__executions__execution_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/analyses/{analysis_id}/report.html": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Analysis Report Html */
    get: operations["get_analysis_report_html_api_v1_analyses__analysis_id__report_html_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/analyses/{analysis_id}/runbook": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Analysis Runbook
     * @description The runbook Markdown exactly as analyzed, as a text download.
     */
    get: operations["get_analysis_runbook_api_v1_analyses__analysis_id__runbook_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/dr/analyze": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Analyze
     * @description Analyze server-side files, given as paths relative to `API_ALLOWED_DIR`.
     */
    get: operations["get_analyze_api_v1_dr_analyze_get"];
    put?: never;
    /**
     * Post Analyze
     * @description Analyze an uploaded runbook: multipart (`runbook` + optional `inventory` files) or JSON.
     */
    post: operations["post_analyze_api_v1_dr_analyze_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/dr/jobs/{job_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Job
     * @description Poll a job; `report` is set once `status` is `succeeded`, `error` once `failed`.
     *
     *     Jobs no longer in memory (after a restart) are answered from the history.
     */
    get: operations["get_job_api_v1_dr_jobs__job_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/dr/jobs/{job_id}/report.html": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Job Report Html
     * @description The finished job's report as a self-contained HTML download (autoescaped).
     */
    get: operations["get_job_report_html_api_v1_dr_jobs__job_id__report_html_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/dr/samples": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Samples
     * @description Sample runbooks and inventories, as paths relative to `API_ALLOWED_DIR`.
     */
    get: operations["list_samples_api_v1_dr_samples_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/dr/samples/file": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Sample
     * @description The text of one sample file (a path from `GET /api/v1/dr/samples`).
     */
    get: operations["get_sample_api_v1_dr_samples_file_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/execution/settings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Execution Settings
     * @description Whether execution is available, so a client can explain why it is not.
     */
    get: operations["execution_settings_api_v1_execution_settings_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/executions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Executions */
    get: operations["list_executions_api_v1_executions_get"];
    put?: never;
    /**
     * Create Execution
     * @description Plan an execution from a finished analysis; it follows the report's execution plan.
     *
     *     `409 CONFLICT` while the analysis is unfinished or failed. Stored analyses
     *     work after a restart too. `mode: live` needs `EXECUTION_ALLOW_LIVE=true`.
     */
    post: operations["create_execution_api_v1_executions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/executions/{execution_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Execution Detail */
    get: operations["get_execution_detail_api_v1_executions__execution_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/executions/{execution_id}/audit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Audit */
    get: operations["get_audit_api_v1_executions__execution_id__audit_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/executions/{execution_id}/steps/{step_number}/approve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Approve
     * @description Approve the call with the hash you were shown (`409 STALE_CALL` if it changed).
     */
    post: operations["approve_api_v1_executions__execution_id__steps__step_number__approve_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/executions/{execution_id}/steps/{step_number}/call": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Set Call
     * @description Accept (omit `call`) or replace a call. Clears the step's approvals.
     */
    put: operations["set_call_api_v1_executions__execution_id__steps__step_number__call_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/executions/{execution_id}/steps/{step_number}/{action}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Decide */
    post: operations["decide_api_v1_executions__execution_id__steps__step_number___action__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/executions/{execution_id}/{action}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Change Execution
     * @description Lifecycle. `abort` is the kill switch; calls already sent become `UNKNOWN`.
     */
    post: operations["change_execution_api_v1_executions__execution_id___action__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_v1_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/services/{service_name}/history": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Service History
     * @description Measured facts from this service's stored analyses and finished live runs (ADR 0009).
     *
     *     Steps are keyed by fingerprint; a report's `historicalInsights` has them matched
     *     to that runbook's step numbers instead.
     */
    get: operations["get_service_history_api_v1_services__service_name__history_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tools": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Tools
     * @description Allow-listed tools with their effective risk class (never server credentials).
     */
    get: operations["list_tools_api_v1_tools_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AnalysisDetail */
    AnalysisDetail: {
      provenance: components["schemas"]["Provenance"];
      report: components["schemas"]["DRReadinessReport"];
      /**
       * Stale
       * @description Older than HISTORY_STALE_AFTER_HOURS; health may differ now
       */
      stale: boolean;
      summary: components["schemas"]["AnalysisSummary"];
    };
    /** AnalysisPage */
    AnalysisPage: {
      /** Items */
      items: components["schemas"]["AnalysisSummary"][];
      /**
       * Nextbefore
       * @description Pass as `before` for the next page; null on the last page
       */
      nextBefore?: string | null;
    };
    /**
     * AnalysisRef
     * @description The readiness analysis an execution was created from (API and CLI require one).
     */
    AnalysisRef: {
      /** Aianalysisavailable */
      aiAnalysisAvailable: boolean;
      /**
       * Analyzedat
       * Format: date-time
       */
      analyzedAt: string;
      /** Jobid */
      jobId: string;
      /** Risklevel */
      riskLevel: string;
      /** Riskscore */
      riskScore: number;
    };
    /**
     * AnalysisSource
     * @enum {string}
     */
    AnalysisSource: "api" | "cli";
    /** AnalysisSummary */
    AnalysisSummary: {
      /** Aianalysisavailable */
      aiAnalysisAvailable: boolean;
      /**
       * Completedat
       * Format: date-time
       */
      completedAt: string;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /** Executioncount */
      executionCount: number;
      /** Id */
      id: string;
      /** Inventorylabel */
      inventoryLabel: string | null;
      /** Owner */
      owner: string;
      riskLevel: components["schemas"]["RiskLevel"];
      /** Riskscore */
      riskScore: number;
      /** Rtofeasible */
      rtoFeasible: boolean;
      /** Runbooklabel */
      runbookLabel: string;
      /** Servicename */
      serviceName: string;
      source: components["schemas"]["AnalysisSource"];
    };
    /**
     * AnalyzeJsonRequest
     * @description JSON form of `POST /api/v1/dr/analyze` (the brief's `{ runbookMarkdown, inventory? }`).
     */
    AnalyzeJsonRequest: {
      /** @default null */
      inventory: components["schemas"]["SystemInventory"] | null;
      /**
       * Runbookmarkdown
       * @description The runbook as Markdown text.
       */
      runbookMarkdown: string;
      /**
       * Runbookname
       * @description Label for report meta.runbookFile.
       * @default null
       */
      runbookName: string | null;
    };
    /** Approval */
    Approval: {
      /** Approver */
      approver: string;
      /** Callhash */
      callHash: string;
      /** Comment */
      comment?: string | null;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /** Verifyhash */
      verifyHash?: string | null;
    };
    /** ApproveRequest */
    ApproveRequest: {
      /** Approver */
      approver: string;
      /**
       * Callhash
       * @description The hash the approver was shown
       */
      callHash: string;
      /** Comment */
      comment?: string | null;
      /**
       * Kind
       * @default main
       * @enum {string}
       */
      kind: "main" | "rollback";
    };
    /** AuditEvent */
    AuditEvent: {
      /** Actor */
      actor: string;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /** Executionid */
      executionId: string;
      /** Hash */
      hash: string;
      /** Payload */
      payload?: {
        [key: string]: components["schemas"]["JsonValue"];
      };
      /** Prevhash */
      prevHash: string;
      /** Seq */
      seq: number;
      /** Type */
      type: string;
    };
    /** AuditView */
    AuditView: {
      /** Events */
      events: components["schemas"]["AuditEvent"][];
      verification?: components["schemas"]["ChainVerification"] | null;
    };
    /**
     * CallKind
     * @enum {string}
     */
    CallKind: "main" | "verify" | "rollback";
    /**
     * CallRequest
     * @description Replace a call, or accept it as it is (`call` omitted on the main call).
     */
    CallRequest: {
      call?: components["schemas"]["PlannedToolCall"] | null;
      /** Editor */
      editor: string;
      /** @default main */
      kind: components["schemas"]["CallKind"];
    };
    /**
     * CallSource
     * @enum {string}
     */
    CallSource: "annotated" | "ai_proposed" | "edited";
    /** ChainVerification */
    ChainVerification: {
      /** Brokenatseq */
      brokenAtSeq?: number | null;
      /** Events */
      events: number;
      /** Head */
      head: string;
      /** Valid */
      valid: boolean;
    };
    /**
     * CreateExecutionRequest
     * @description An execution is always created from a finished readiness analysis.
     */
    CreateExecutionRequest: {
      /**
       * Analysisjobid
       * @description A succeeded analysis job
       */
      analysisJobId: string;
      /** @default dry_run */
      mode: components["schemas"]["ExecutionMode"];
      /** Startedby */
      startedBy: string;
    };
    /** DRReadinessReport */
    DRReadinessReport: {
      /**
       * Aianalysisavailable
       * @default true
       */
      aiAnalysisAvailable: boolean;
      /** Ainote */
      aiNote?: string | null;
      /** Dependencyhealth */
      dependencyHealth?: components["schemas"]["DependencyHealth"][];
      /** Executionplan */
      executionPlan?: components["schemas"]["ExecutionPhase"][];
      /** Gapanalysis */
      gapAnalysis?: components["schemas"]["Gap"][];
      historicalInsights?: components["schemas"]["ServiceHistory"] | null;
      meta: components["schemas"]["ReportMeta"];
      readonly riskLevel: components["schemas"]["RiskLevel"];
      /** Riskscore */
      riskScore: number;
      rtoAnalysis: components["schemas"]["RtoAnalysis"];
      serviceSummary: components["schemas"]["ServiceSummary"];
      /** Singlepointsoffailure */
      singlePointsOfFailure?: components["schemas"]["SinglePointOfFailure"][];
      /** Suggestions */
      suggestions?: components["schemas"]["Suggestion"][];
      /** Summary */
      summary: string;
    };
    /** DependencyHealth */
    DependencyHealth: {
      actualStatus: components["schemas"]["DependencyStatus"];
      /**
       * Impact
       * @description Which steps are affected
       */
      impact: string;
      /** Name */
      name: string;
      /**
       * Runbookassumes
       * @default available
       * @constant
       */
      runbookAssumes: "available";
    };
    /**
     * DependencyStatus
     * @description Health as seen from a runbook dependency; adds the not-in-inventory case.
     * @enum {string}
     */
    DependencyStatus: "UP" | "DOWN" | "UNREACHABLE" | "NOT_IN_INVENTORY";
    /** DependencyTrend */
    DependencyTrend: {
      /** Analyses */
      analyses: number;
      /**
       * Down
       * @default 0
       */
      down: number;
      /** Name */
      name: string;
      /**
       * Notininventory
       * @default 0
       */
      notInInventory: number;
      /**
       * Unreachable
       * @default 0
       */
      unreachable: number;
      /**
       * Up
       * @default 0
       */
      up: number;
    };
    /**
     * ErrorBody
     * @description The shared error shape: `{error, code, details?}`.
     */
    ErrorBody: {
      /** Code */
      code: string;
      /** Details */
      details?: {
        [key: string]: unknown;
      } | null;
      /** Error */
      error: string;
    };
    /** Execution */
    Execution: {
      analysis?: components["schemas"]["AnalysisRef"] | null;
      /**
       * Audithead
       * @default
       */
      auditHead: string;
      /**
       * Auditseq
       * @default 0
       */
      auditSeq: number;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /** Id */
      id: string;
      mode: components["schemas"]["ExecutionMode"];
      /** Pausereason */
      pauseReason?: string | null;
      /** Runbooklabel */
      runbookLabel: string;
      /** Runbooksha256 */
      runbookSha256: string;
      /** Startedby */
      startedBy: string;
      /** @default CREATED */
      state: components["schemas"]["ExecutionState"];
      /** Steps */
      steps: components["schemas"]["StepRun"][];
      /**
       * Toolcallsused
       * @default 0
       */
      toolCallsUsed: number;
      /**
       * Updatedat
       * Format: date-time
       */
      updatedAt: string;
    };
    /**
     * ExecutionMode
     * @enum {string}
     */
    ExecutionMode: "dry_run" | "live";
    /** ExecutionOutcome */
    ExecutionOutcome: {
      /** Elapsedminutes */
      elapsedMinutes: number;
      /** Executionid */
      executionId: string;
      /**
       * Startedat
       * Format: date-time
       */
      startedAt: string;
      /**
       * State
       * @enum {string}
       */
      state: "COMPLETED" | "FAILED" | "ABORTED";
      /** Statedrtominutes */
      statedRtoMinutes: number;
    };
    /** ExecutionPhase */
    ExecutionPhase: {
      /** Estimatedminutes */
      estimatedMinutes: number;
      /**
       * Gate
       * @description What must be true before proceeding
       */
      gate: string;
      /** Phase */
      phase: number;
      /**
       * Steps
       * @description Steps that can run in parallel
       */
      steps: number[];
    };
    /** ExecutionSettingsView */
    ExecutionSettingsView: {
      /** Allowlive */
      allowLive: boolean;
      /** Approvaltimeoutminutes */
      approvalTimeoutMinutes: number;
      /** Approvalsbyrisk */
      approvalsByRisk: {
        [key: string]: number;
      };
      /** Enabled */
      enabled: boolean;
      /**
       * Identityverified
       * @default false
       * @constant
       */
      identityVerified: false;
      /** Maxtoolcalls */
      maxToolCalls: number;
    };
    /**
     * ExecutionState
     * @enum {string}
     */
    ExecutionState: "CREATED" | "RUNNING" | "PAUSED" | "COMPLETED" | "FAILED" | "ABORTED";
    /** ExecutionSummary */
    ExecutionSummary: {
      /** Analysisjobid */
      analysisJobId: string | null;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /** Id */
      id: string;
      mode: components["schemas"]["ExecutionMode"];
      /** Runbooklabel */
      runbookLabel: string;
      /** Startedby */
      startedBy: string;
      state: components["schemas"]["ExecutionState"];
      /** Steps */
      steps: number;
      /**
       * Updatedat
       * Format: date-time
       */
      updatedAt: string;
    };
    /** Gap */
    Gap: {
      /** Description */
      description: string;
      /** Recommendation */
      recommendation: string;
      severity: components["schemas"]["Severity"];
      type: components["schemas"]["GapType"];
    };
    /**
     * GapType
     * @enum {string}
     */
    GapType:
      | "MISSING_STEP"
      | "VAGUE_INSTRUCTION"
      | "NO_VALIDATION"
      | "MISSING_ROLLBACK"
      | "UNVERIFIED_DEPENDENCY"
      | "OWNER_AMBIGUITY"
      | "HISTORICAL";
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Status
       * @default ok
       * @constant
       */
      status: "ok";
      /**
       * Uptime
       * @description Seconds since the API started.
       */
      uptime: number;
      /** Version */
      version: string;
    };
    /**
     * HealthStatus
     * @enum {string}
     */
    HealthStatus: "UP" | "DOWN" | "UNREACHABLE";
    /** InventoryService */
    InventoryService: {
      /**
       * Endpoint
       * Format: uri
       */
      endpoint: string;
      /**
       * Expectedstatus
       * @default UP
       * @constant
       */
      expectedStatus: "UP";
      /**
       * Mocklatencyms
       * @default null
       */
      mockLatencyMs: number | null;
      /** @default UP */
      mockStatus: components["schemas"]["HealthStatus"];
      /** Name */
      name: string;
      /**
       * Region
       * @default null
       */
      region: string | null;
      type: components["schemas"]["InventoryServiceType"];
    };
    /**
     * InventoryServiceType
     * @enum {string}
     */
    InventoryServiceType: "database" | "messaging" | "secrets" | "compute" | "network" | "external";
    /**
     * JobState
     * @enum {string}
     */
    JobState: "pending" | "running" | "succeeded" | "failed";
    /** JobView */
    JobView: {
      /** Completedat */
      completedAt?: string | null;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      error?: components["schemas"]["ErrorBody"] | null;
      /**
       * Historysaved
       * @description Whether the report was stored (null while history is off)
       */
      historySaved?: boolean | null;
      /** Jobid */
      jobId: string;
      report?: components["schemas"]["DRReadinessReport"] | null;
      status: components["schemas"]["JobState"];
    };
    JsonValue: unknown;
    /**
     * LifecycleRequest
     * @description `pause`, `abort` and `close` need a reason; `start` and `resume` do not.
     */
    LifecycleRequest: {
      /** Actor */
      actor: string;
      /** Reason */
      reason?: string | null;
    };
    /**
     * PlannedToolCall
     * @description A tool call written in a runbook annotation: `<server>/<tool> {JSON arguments}`.
     *
     *     Untrusted input like any other runbook text: it is only a request, checked
     *     against the execution policy and approved by humans before anything runs.
     */
    PlannedToolCall: {
      /** Arguments */
      arguments?: {
        [key: string]: components["schemas"]["JsonValue"];
      };
      /** Server */
      server: string;
      /** Tool */
      tool: string;
    };
    /**
     * ProposalNote
     * @description Why the model proposed a step's call; untrusted text, shown to reviewers as-is.
     */
    ProposalNote: {
      /** Confidence */
      confidence?: string | null;
      /**
       * Rationale
       * @default
       */
      rationale: string;
    };
    /**
     * Provenance
     * @description How a report was produced; never the API key or base URL.
     */
    Provenance: {
      /** Agentversion */
      agentVersion: string;
      /** Llmmodel */
      llmModel?: string | null;
      /** Llmprovider */
      llmProvider: string;
      /** Promptversion */
      promptVersion: string;
    };
    /** ReportMeta */
    ReportMeta: {
      /** Agentversion */
      agentVersion: string;
      /** Analysistimems */
      analysisTimeMs: number;
      /**
       * Analyzedat
       * Format: date-time
       */
      analyzedAt: string;
      /** Inventoryfile */
      inventoryFile: string;
      /** Runbookfile */
      runbookFile: string;
    };
    /**
     * RiskClass
     * @enum {string}
     */
    RiskClass: "read" | "write" | "destructive";
    /**
     * RiskLevel
     * @enum {string}
     */
    RiskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
    /** RtoAnalysis */
    RtoAnalysis: {
      /** Bottlenecksteps */
      bottleneckSteps?: number[];
      /**
       * Bufferminutes
       * @description Stated RTO minus estimated total; may be negative
       */
      bufferMinutes: number;
      /** Feasible */
      feasible: boolean;
      /** Statedrtominutes */
      statedRtoMinutes: number;
      /** Totalestimatedminutes */
      totalEstimatedMinutes: number;
    };
    /** SampleFile */
    SampleFile: {
      /** Content */
      content: string;
      /** Path */
      path: string;
    };
    /**
     * SampleList
     * @description Paths relative to `API_ALLOWED_DIR`, usable with `GET /api/v1/dr/analyze`.
     */
    SampleList: {
      /** Inventories */
      inventories: string[];
      /** Runbooks */
      runbooks: string[];
    };
    /**
     * ServiceHistory
     * @description Facts computed by code from stored analyses and live executions only.
     */
    ServiceHistory: {
      /** Analysesconsidered */
      analysesConsidered: number;
      /** Dependencies */
      dependencies?: components["schemas"]["DependencyTrend"][];
      /**
       * Dryruns
       * @description Counted but never measured
       */
      dryRuns: number;
      /**
       * Executions
       * @description Newest first
       */
      executions?: components["schemas"]["ExecutionOutcome"][];
      /** Liveruns */
      liveRuns: number;
      /**
       * Riskscores
       * @description Oldest first
       */
      riskScores?: number[];
      /** Servicename */
      serviceName: string;
      /** Steps */
      steps?: components["schemas"]["StepHistory"][];
    };
    /** ServiceSummary */
    ServiceSummary: {
      /** Name */
      name: string;
      /** Owner */
      owner: string;
      /**
       * Statedrpo
       * @description Minutes
       */
      statedRPO: number;
      /**
       * Statedrto
       * @description Minutes
       */
      statedRTO: number;
    };
    /**
     * Severity
     * @enum {string}
     */
    Severity: "LOW" | "MEDIUM" | "HIGH";
    /** SinglePointOfFailure */
    SinglePointOfFailure: {
      /** Affectedsteps */
      affectedSteps?: number[];
      /** Description */
      description: string;
      /** Mitigationsuggestion */
      mitigationSuggestion: string;
    };
    /**
     * StepDecisionRequest
     * @description `reject`, `skip` and `manual` need a reason; `verify` needs `succeeded`.
     */
    StepDecisionRequest: {
      /** Actor */
      actor: string;
      /** Reason */
      reason?: string | null;
      /** Succeeded */
      succeeded?: boolean | null;
    };
    /** StepHistory */
    StepHistory: {
      /** Estimatedminutes */
      estimatedMinutes: number;
      /**
       * Failed
       * @default 0
       */
      failed: number;
      /**
       * Fingerprint
       * @description SHA-256 of the normalized action and target system
       */
      fingerprint: string;
      /** Liveruns */
      liveRuns: number;
      /**
       * Manualdone
       * @default 0
       */
      manualDone: number;
      /** Maxactiveminutes */
      maxActiveMinutes?: number | null;
      /**
       * Medianactiveminutes
       * @description Running (or manual) until the step's final state
       */
      medianActiveMinutes?: number | null;
      /**
       * Medianelapsedminutes
       * @description Including approval waits after the run started
       */
      medianElapsedMinutes?: number | null;
      /**
       * Retries
       * @default 0
       */
      retries: number;
      /**
       * Rolledback
       * @default 0
       */
      rolledBack: number;
      /**
       * Skipped
       * @default 0
       */
      skipped: number;
      /**
       * Stepnumber
       * @description In the runbook it was matched to
       */
      stepNumber: number;
      /**
       * Succeeded
       * @default 0
       */
      succeeded: number;
      /** Targetsystem */
      targetSystem?: string | null;
      /**
       * Unknown
       * @default 0
       */
      unknown: number;
    };
    /** StepRun */
    StepRun: {
      /** Action */
      action: string;
      /**
       * Attempt
       * @default 1
       */
      attempt: number;
      call?: components["schemas"]["ToolCall"] | null;
      /** Dependson */
      dependsOn?: number[];
      /** Estimatedminutes */
      estimatedMinutes: number;
      /** Owner */
      owner: string;
      /** Phase */
      phase: number;
      /** Policyerrors */
      policyErrors?: string[];
      proposal?: components["schemas"]["ProposalNote"] | null;
      rollback?: components["schemas"]["ToolCall"] | null;
      /** @default PLANNED */
      state: components["schemas"]["StepState"];
      /** Stepnumber */
      stepNumber: number;
      /** Summary */
      summary?: string | null;
      /** Targetsystem */
      targetSystem?: string | null;
      verify?: components["schemas"]["ToolCall"] | null;
      /** Waitingsince */
      waitingSince?: string | null;
    };
    /**
     * StepState
     * @enum {string}
     */
    StepState:
      | "PLANNED"
      | "PROPOSED"
      | "AWAITING_APPROVAL"
      | "APPROVED"
      | "REJECTED"
      | "RUNNING"
      | "VERIFYING"
      | "SUCCEEDED"
      | "FAILED"
      | "UNKNOWN"
      | "ROLLED_BACK"
      | "AWAITING_MANUAL"
      | "MANUAL_DONE"
      | "SKIPPED";
    /**
     * StoredExecution
     * @description A past execution of an analysis, read-only: its steps and its verified audit log.
     */
    StoredExecution: {
      audit: components["schemas"]["AuditView"];
      execution: components["schemas"]["Execution"];
    };
    /** Suggestion */
    Suggestion: {
      /** Detail */
      detail: string;
      /** Priority */
      priority: number;
      /** Title */
      title: string;
    };
    /** SystemInventory */
    SystemInventory: {
      /** Services */
      services?: components["schemas"]["InventoryService"][];
    };
    /** ToolCall */
    ToolCall: {
      /** Approvals */
      approvals?: components["schemas"]["Approval"][];
      /** Arguments */
      arguments?: {
        [key: string]: components["schemas"]["JsonValue"];
      };
      /** Callhash */
      callHash: string;
      /** Error */
      error?: string | null;
      /** Finishedat */
      finishedAt?: string | null;
      kind: components["schemas"]["CallKind"];
      result?: components["schemas"]["ToolResult"] | null;
      riskClass?: components["schemas"]["RiskClass"] | null;
      /** Server */
      server: string;
      source: components["schemas"]["CallSource"];
      /** Startedat */
      startedAt?: string | null;
      /** Tool */
      tool: string;
    };
    /**
     * ToolResult
     * @description Outcome of one call. `ok=False` is a tool-level failure reported by the server.
     */
    ToolResult: {
      /**
       * Content
       * @default
       */
      content: string;
      /** Ok */
      ok: boolean;
      /**
       * Simulated
       * @default false
       */
      simulated: boolean;
      /** Structured */
      structured?: {
        [key: string]: components["schemas"]["JsonValue"];
      } | null;
    };
    /** ToolView */
    ToolView: {
      /** Description */
      description: string;
      /** Inputschema */
      inputSchema: {
        [key: string]: components["schemas"]["JsonValue"];
      };
      /** Name */
      name: string;
      risk: components["schemas"]["RiskClass"];
      /** Server */
      server: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_analyses_api_v1_analyses_get: {
    parameters: {
      query?: {
        service?: string | null;
        riskLevel?: components["schemas"]["RiskLevel"] | null;
        limit?: number;
        /** @description `nextBefore` of the last page */
        before?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AnalysisPage"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  get_analysis_api_v1_analyses__analysis_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        analysis_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AnalysisDetail"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  delete_analysis_api_v1_analyses__analysis_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        analysis_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  get_analysis_executions_api_v1_analyses__analysis_id__executions_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        analysis_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExecutionSummary"][];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  get_analysis_execution_api_v1_analyses__analysis_id__executions__execution_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        analysis_id: string;
        execution_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StoredExecution"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  get_analysis_report_html_api_v1_analyses__analysis_id__report_html_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        analysis_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/html": string;
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/html": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/html": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/html": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/html": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  get_analysis_runbook_api_v1_analyses__analysis_id__runbook_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        analysis_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": string;
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  get_analyze_api_v1_dr_analyze_get: {
    parameters: {
      query: {
        runbook: string;
        inventory?: string | null;
        /** @description Wait (bounded) and return the report if done. */
        wait?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description wait=true and the job finished in time */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DRReadinessReport"];
        };
      };
      /** @description Job accepted; poll the Location header */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobView"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  post_analyze_api_v1_dr_analyze_post: {
    parameters: {
      query?: {
        /** @description Wait (bounded) and return the report if done. */
        wait?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AnalyzeJsonRequest"];
        "multipart/form-data": {
          /** Format: binary */
          inventory?: string;
          /** Format: binary */
          runbook: string;
        };
      };
    };
    responses: {
      /** @description wait=true and the job finished in time */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DRReadinessReport"];
        };
      };
      /** @description Job accepted; poll the Location header */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobView"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  get_job_api_v1_dr_jobs__job_id__get: {
    parameters: {
      query?: {
        /** @description Wait (bounded) and return the report if done. */
        wait?: boolean;
      };
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobView"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_job_report_html_api_v1_dr_jobs__job_id__report_html_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/html": string;
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/html": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/html": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_samples_api_v1_dr_samples_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SampleList"];
        };
      };
    };
  };
  get_sample_api_v1_dr_samples_file_get: {
    parameters: {
      query: {
        path: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SampleFile"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  execution_settings_api_v1_execution_settings_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExecutionSettingsView"];
        };
      };
    };
  };
  list_executions_api_v1_executions_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExecutionSummary"][];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Bad Gateway */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  create_execution_api_v1_executions_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateExecutionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Execution"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Bad Gateway */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  get_execution_detail_api_v1_executions__execution_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        execution_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Execution"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Bad Gateway */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  get_audit_api_v1_executions__execution_id__audit_get: {
    parameters: {
      query?: {
        /** @description Recompute the hash chain */
        verify?: boolean;
      };
      header?: never;
      path: {
        execution_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuditView"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Bad Gateway */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  approve_api_v1_executions__execution_id__steps__step_number__approve_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        execution_id: string;
        step_number: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApproveRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Execution"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Bad Gateway */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  set_call_api_v1_executions__execution_id__steps__step_number__call_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        execution_id: string;
        step_number: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CallRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Execution"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Bad Gateway */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  decide_api_v1_executions__execution_id__steps__step_number___action__post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        execution_id: string;
        step_number: number;
        action: "reject" | "skip" | "manual" | "mark-done" | "verify" | "retry" | "rollback";
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StepDecisionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Execution"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Bad Gateway */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  change_execution_api_v1_executions__execution_id___action__post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        execution_id: string;
        action: "start" | "pause" | "resume" | "abort" | "close";
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LifecycleRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Execution"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Bad Gateway */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  health_api_v1_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  get_service_history_api_v1_services__service_name__history_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        service_name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceHistory"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
  list_tools_api_v1_tools_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ToolView"][];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
      /** @description Bad Gateway */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorBody"];
        };
      };
    };
  };
}
